task_file: /Users/david/Desktop/due/todo.json
color:
  task_id: '#14A2D2'   # blue
  task_name: '#FFFFFF' # white
  deadline: '#FEA971' #orange
  complete: '#196719 reverse' #green highlight
  guide_line: '#FFFFFF' # white